CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT, 
    username VARCHAR(32) NOT NULL,
    password VARCHAR(256) NOT NULL,
    public BOOLEAN NOT NULL DEFAULT 0,
    admin BOOLEAN NOT NULL DEFAULT 0
);